<style>
	.my-block{
		margin: 100px 0px;
	}
</style>
<div class="col-md-12 my-block">
	<div class="col-md-4 col-md-offset-4">
		<?php 
			foreach ($role as $key => $value) { ?>
			<a href="/access/index/office?role_name=<?php echo $value->role_name;?>&id=<?php echo $value->id; ?>" class="btn btn-primary btn-lg btn-block""><?php echo $value->role_name; ?></a>
				
		<?php } ?>
	</div>
</div>
<div class="col-sm-12">  
    <a href="/user/auth" class="btn btn-info">Назад</a>
</div> 