<style>
    .myClass{
        /*border: 1px solid black;*/
        margin-top: 10px;
    }
    .btnCategory{
        margin-left: 15px;
        margin-top: 10px;

    }
</style>
<?php
    $sumCosts = 0;
    $form = $this->form;
    $form->setAttribute('action', '/money/profit/profit');
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('id_category'));
?>
<div class="row myClass">
    <div class="col-md-12  myClass"><h1 class="text-center">Доходы</h1></div>
</div>
<div class="hidden">
    <?php echo $this->formRow($form->get('submit')); ?>    
</div>
<div class="row myClass">
    <div class="col-md-4 col-md-offset-4  myClass"><?php echo $this->formRow($form->get('sum')); ?></div>
</div>
<?php echo $this->form()->closeTag(); ?>
 
<div class="row myClass">
    <?php foreach ($categoryProfit as $key => $value) { 
        $arrCategory[$value->id] = $value->name_profit; ?>
        <button class="btnCategory col-md-1 btn btn-primary" id="<?php echo $value->id;?>" onclick="return EntryCategory(<?php echo $value->id;?>);"><?php echo $value->name_profit; ?></button>
    <?php } ?>
</div>
<div class="row myClass">
    <div class="col-md-4 col-md-offset-4 myClass"><?=(isset($error)?$error:"")?></div>
</div>
<div class="row myClass table-responsive">
    <table class="table table-striped">
        <tr>
            <td>№</td>
            <td>Дата</td>
            <td>Категория</td>
            <td>Сумма</td>            
            <td></td>
        </tr>
        <?php $i = 0; foreach ($profitUser as $key => $value) { ;?>
        <tr>
            <td class="col-md-1"><?php echo $i+=1; ?></td>
            <td class="col-md-1"><?php echo $value->date; ?></td>            
            <td class="col-md-1"><?php echo $arrCategory["$value->id_category"]; ?></td>            
            <td class="col-md-1"><?php echo $value->sum; $sumCosts+=$value->sum; ?></td>  
            <td class="col-md-1"> <a  class="btn btn-danger" href="/money/profit/delete-profit?id=<?php echo $value->id ?>">Удалить</a></td>  
        </tr>
        <?php } ?>        
        <tr class="info">
            <td class="col-md-1"><strong>Всего</strong></td>
            <td class="col-md-1"></td>            
            <td class="col-md-2"></td>            
            <td class="col-md-1"><strong><?php echo $sumCosts; ?></strong></td>  
            <td class="col-md-1 info"></td>  
        </tr>
    </table>
</div>
<div class="row myClass">
    <div class="col-md-1 myClass"><a  class="btn btn-info" href="/user/auth">Назад</a></div>
</div>

<script>  
  function EntryCategory(id) {
    $('input[type="hidden"]').val(id)
    $("#submitAdd").click();    
}
</script>