<div class="table-responsive">
    <table class="table table-striped">
        <tr >
            <td>№</td>        
            <td>Дата</td>
            <td>IP</td>               
        </tr> 
        <?php $i = 1; foreach ($history as $key => $value){?>
        <tr>
            <td> <?php echo $i++; ?></td>
            <td> <?php echo $value->date; ?></td>
            <td> <?php echo $value->ip; ?></td>
        </tr>    
         <?php } ?> 
    </table>
</div>
<div class="col-sm-12">  
    <a href="/user/auth" class="btn btn-info">Назад</a>
</div> 
