<style>
    .my-block{
        margin: 20px 0px 100px 0px;
    }
    input{
        margin: 5px;        
    }
    label{
        margin: 10px 0;
    }
    .btnRole{
        margin-top: 5px;
    }
</style>
<div class="col-md-12 my-block">    
        <div class="col-md-4 col-md-offset-4">
            <?php
                $form = $this->form;
                $form->setAttribute('action', '/administer/index/edit-user');
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formRow($form->get('id'));
                echo $this->formRow($form->get('role')); 
            ?>     
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-3 control-label">Логин</label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($form->get('login')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-3 control-label">Email</label>
                    <div class="col-sm-9">
                        <?php echo $this->formRow($form->get('email')); ?>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-3 control-label">Роль</label>
                    <div class="col-sm-9">
                        <?php foreach ($arrayRole as $id => $role_name) {
                            if($role_name != "guest"){
                        ?>
                           <div class="btnRole col-md-12 btn btn-primary" onclick='entryRole("<?php echo $role_name;?>")'><?php echo $role_name;?></div>
                        <?php }} ?>
                    </div>
                </div> 
                <div class="form-group"> 
                    <div class="col-sm-12">                            
                        <?php echo $this->formRow($form->get('submit')); ?>
                    </div> 
                </div> 
                <?php    
                    echo $this->form()->closeTag();
                ?>                
                <div class="form-group">   
                    <div class="col-md-12"><?=(isset($error[0])?$error[0]:"") ?></div> 
                </div> 
        </div>
        <div class="form-group">                     
            <div class="col-sm-12">  
                <a href="/administer/index/user" class="btn btn-info">Назад</a>
            </div> 
        </div>     
</div>
<script>  
  function entryRole(role_name) {
    // var name = role_name;
    // $().val();
    var name = $('input[name="role"]').val(role_name);
    console.log(name[0]);
}
</script>

            
